const state = {
  ingredients: [
    // Normal
    {
      'id': 'normal_meat',
      'level': 'normal',
      'type': 'meat',
      'name': 'Meat',
      'icon': 'M',
      'image': 'images/ingredient_meat_1.png',
      'puzzle_shape': ['MMMM', ],
      'possibilities': [
        [
          'MMMM_',
          '_____',
          '_____',
          '_____',
          '_____',
        ],
        [
          '_____',
          'MMMM_',
          '_____',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_____',
          'MMMM_',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          'MMMM_',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          '_____',
          'MMMM_',
        ],
        [
          '_MMMM',
          '_____',
          '_____',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_MMMM',
          '_____',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_MMMM',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_____',
          '_MMMM',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_____',
          '_____',
          '_MMMM',
        ],
      ],
    },
    {
      'id': 'normal_veget',
      'level': 'normal',
      'type': 'veget',
      'name': 'Vegitable',
      'icon': 'V',
      image: 'images/ingredient_vege_1.png',
      'puzzle_shape': [
        'V_V_', 
        '_V_V',
      ],
      possibilities: [
        [
          'V_V__', 
          '_V_V_',
          '_____',
          '_____',
          '_____',
        ],
        [
          '_____',
          'V_V__', 
          '_V_V_',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_____',
          'V_V__', 
          '_V_V_',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          'V_V__', 
          '_V_V_',
        ],
        [
          '_V_V_', 
          '__V_V',
          '_____',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_V_V_', 
          '__V_V',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_V_V_', 
          '__V_V',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_____',
          '_V_V_', 
          '__V_V',
        ],
      ],
    },
    {
      id: 'normal_flour',
      level: 'normal',
      type: 'flour',
      name: 'Flour & Grain',
      icon: 'F',
      'image': 'images/ingredient_flourgrain_1.png',
      puzzle_shape: [
        '_F_',
        'F_F',
        '_F_',
      ],
      possibilities: [
        [
          '_F___',
          'F_F__',
          '_F___',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_F___',
          'F_F__',
          '_F___',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_F___',
          'F_F__',
          '_F___',
        ],
        [
          '__F__',
          '_F_F_',
          '__F__',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '__F__',
          '_F_F_',
          '__F__',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '__F__',
          '_F_F_',
          '__F__',
        ],
        [
          '___F_',
          '__F_F',
          '___F_',
          '_____',
          '_____',
        ],      
        [       
          '_____',
          '___F_',
          '__F_F',
          '___F_',
          '_____',
        ],      
        [       
          '_____',
          '_____',
          '___F_',
          '__F_F',
          '___F_',
        ],
      ],
    },
    {
      id: 'normal_seafood',
      level: 'normal',
      type: 'seafood',
      name: 'Seafood',
      icon: 'S',
      image: 'images/ingredient_seafood_1.png',
      puzzle_shape: [
        'S__',
        '_S_',
        'S_S',
      ],
      possibilities: [
        [
          'S____',
          '_S___',
          'S_S__',
          '_____',
          '_____',
        ],
        [
          '_____',
          'S____',
          '_S___',
          'S_S__',
          '_____',
        ],
        [
          '_____',
          '_____',
          'S____',
          '_S___',
          'S_S__',
        ],
        [
          '_S___',
          '__S__',
          '_S_S_',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_S___',
          '__S__',
          '_S_S_',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_S___',
          '__S__',
          '_S_S_',
        ],
        [
          '__S__',
          '___S_',
          '__S_S',
          '_____',
          '_____',
        ],   
        [    
          '_____',
          '__S__',
          '___S_',
          '__S_S',
          '_____',
        ],   
        [    
          '_____',
          '_____',
          '__S__',
          '___S_',
          '__S_S',
        ],
      ],
    },
    {
      id: 'normal_dairy',
      level: 'normal',
      type: 'dairy',
      name: 'Dairy & Egg',
      'image': 'images/ingredient_dairyegg_1.png',
      icon: 'D',
      puzzle_shape: [
        '_D__',
        'D___',
        '_D_D',
      ],
      possibilities: [
        [
          '_D___',
          'D____',
          '_D_D_',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_D___',
          'D____',
          '_D_D_',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_D___',
          'D____',
          '_D_D_',
        ],
        [
          '__D__',
          '_D___',
          '__D_D',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '__D__',
          '_D___',
          '__D_D',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '__D__',
          '_D___',
          '__D_D',
        ],
      ],
    },
    {
      id: 'normal_spice',
      level: 'normal',
      type: 'spice',
      name: 'Spice & Sauce',
      icon: 'A',
      image: 'images/ingredient_spicesauce_1.png',
      puzzle_shape: [
        '_A_',
        '___',
        '_A_',
        'A_A',
      ],
      possibilities: [
        [
          '_A___',
          '_____',
          '_A___',
          'A_A__',
          '_____',
        ],
        [
          '_____',
          '_A___',
          '_____',
          '_A___',
          'A_A__',
        ],
        [
          '__A__',
          '_____',
          '__A__',
          '_A_A_',
          '_____',
        ],  
        [   
          '_____',
          '__A__',
          '_____',
          '__A__',
          '_A_A_',
        ],
        [
          '___A_',
          '_____',
          '___A_',
          '__A_A',
          '_____',
        ],   
        [    
          '_____',
          '___A_',
          '_____',
          '___A_',
          '__A_A',
        ],
      ],
    },
    // Rare
    {
      'id': 'rare_meat',
      'level': 'rare',
      'type': 'meat',
      'name': 'Meat',
      'icon': 'm',
      'image': 'images/ingredient_meat_2.png',
      'puzzle_shape': [
        'm_mm', 
      ],
      possibilities: [
        [
          'm_mm_', 
          '_____',
          '_____',
          '_____',
          '_____',
        ],
        [
          '_____',
          'm_mm_', 
          '_____',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_____',
          'm_mm_', 
          '_____',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          'm_mm_', 
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          '_____',
          'm_mm_', 
        ],
        [
          '_m_mm', 
          '_____',
          '_____',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_m_mm', 
          '_____',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_m_mm', 
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_____',
          '_m_mm', 
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          '_____',
          '_m_mm', 
        ],
      ],
    },
    {
      id: 'rare_veget',
      level: 'rare',
      type: 'veget',
      name: 'Vegitable',
      icon: 'v',
      image: 'images/ingredient_vege_2.png',
      puzzle_shape: [
        'v_v',
        '_v_',
      ],
      possibilities: [
        [
          'v_v__',
          '_v___',
          '_____',
          '_____',
          '_____',
        ],
        [
          '_____',
          'v_v__',
          '_v___',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_____',
          'v_v__',
          '_v___',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          'v_v__',
          '_v___',
        ],
        [
          '_v_v_',
          '__v__',
          '_____',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_v_v_',
          '__v__',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_v_v_',
          '__v__',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_____',
          '_v_v_',
          '__v__',
        ],
        [
          '__v_v',
          '___v_',
          '_____',
          '_____',
          '_____',
        ],      
        [       
          '_____',
          '__v_v',
          '___v_',
          '_____',
          '_____',
        ],      
        [       
          '_____',
          '_____',
          '__v_v',
          '___v_',
          '_____',
        ],      
        [       
          '_____',
          '_____',
          '_____',
          '__v_v',
          '___v_',
        ],
      ],
    },
    {
      id: 'rare_flour',
      level: 'rare',
      type: 'flour',
      name: 'Flour & Grain',
      icon: 'f',
      'image': 'images/ingredient_flourgrain_2.png',
      puzzle_shape: [
        '_f_',
        'f__',
        '_f_',
      ],
      possibilities: [
        [
          '_f___',
          'f____',
          '_f___',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_f___',
          'f____',
          '_f___',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_f___',
          'f____',
          '_f___',
        ],
        [
          '__f__',
          '_f___',
          '__f__',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '__f__',
          '_f___',
          '__f__',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '__f__',
          '_f___',
          '__f__',
        ],
        [
          '___f_',
          '__f__',
          '___f_',
          '_____',
          '_____',
        ],   
        [    
          '_____',
          '___f_',
          '__f__',
          '___f_',
          '_____',
        ],   
        [    
          '_____',
          '_____',
          '___f_',
          '__f__',
          '___f_',
        ],
      ],
    },
    {
      id: 'rare_seafood',
      level: 'rare',
      type: 'seafood',
      name: 'Seafood',
      icon: 's',
      image: 'images/ingredient_seafood_2.png',
      puzzle_shape: [
        's__',
        '_s_',
        '__s',
      ],
      possibilities: [
        [
          's____',
          '_s___',
          '__s__',
          '_____',
          '_____',
        ],
        [
          '_____',
          's____',
          '_s___',
          '__s__',
          '_____',
        ],
        [
          '_____',
          '_____',
          's____',
          '_s___',
          '__s__',
        ],
        [
          '_s___',
          '__s__',
          '___s_',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_s___',
          '__s__',
          '___s_',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_s___',
          '__s__',
          '___s_',
        ],
        [
          '__s__',
          '___s_',
          '____s',
          '_____',
          '_____',
        ],   
        [    
          '_____',
          '__s__',
          '___s_',
          '____s',
          '_____',
        ],   
        [    
          '_____',
          '_____',
          '__s__',
          '___s_',
          '____s',
        ],
      ],
    },
    {
      id: 'rare_dairy',
      level: 'rare',
      type: 'dairy',
      name: 'Dairy',
      icon: 'd',
      'image': 'images/ingredient_dairyegg_2.png',
      puzzle_shape: [
        '_d__',
        'd___',
        '___d',
      ],
      possibilities: [
        [
          '_d___',
          'd____',
          '___d_',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_d___',
          'd____',
          '___d_',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_d___',
          'd____',
          '___d_',
        ],
        [
          '__d__',
          '_d___',
          '____d',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '__d__',
          '_d___',
          '____d',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '__d__',
          '_d___',
          '____d',
        ],
      ],
    },
    {
      id: 'rare_spice',
      level: 'rare',
      type: 'spice',
      name: 'Spice & Sauce',
      icon: 'a',
      image: 'images/ingredient_spicesauce_2.png',
      puzzle_shape: [
        '_a_',
        '___',
        '___',
        'a_a',
      ],
      possibilities: [
        [
          '_a___',
          '_____',
          '_____',
          'a_a__',
          '_____',
        ],
        [
          '_____',
          '_a___',
          '_____',
          '_____',
          'a_a__',
        ],
        [
          '__a__',
          '_____',
          '_____',
          '_a_a_',
          '_____',
        ],  
        [   
          '_____',
          '__a__',
          '_____',
          '_____',
          '_a_a_',
        ],
        [
          '___a_',
          '_____',
          '_____',
          '__a_a',
          '_____',
        ],   
        [    
          '_____',
          '___a_',
          '_____',
          '_____',
          '__a_a',
        ],
      ],
    },
    // Epic,
    {
      id: 'epic_meat',
      level: 'epic',
      type: 'meat',
      name: 'Meat',
      icon: 'n',
      'image': 'images/ingredient_meat_3.png',
      puzzle_shape: [
        'n_n',
      ],
      possibilities: [],
    },
    {
      id: 'epic_veget',
      level: 'epic',
      type: 'veget',
      name: 'Vegtable',
      icon: '^',
      image: 'images/ingredient_vege_3.png',
      puzzle_shape: [
        '_^',
        '^_',
      ],
      possibilities: [
        [
          '_^___',
          '^____',
          '_____',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_^___',
          '^____',
          '_____',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_^___',
          '^____',
          '_____',
        ],
        [
          '_____',
          '_____',
          '_____',
          '_^___',
          '^____',
        ],
        [
          '__^__',
          '_^___',
          '_____',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '__^__',
          '_^___',
          '_____',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '__^__',
          '_^___',
          '_____',
        ],  
        [   
          '_____',
          '_____',
          '_____',
          '__^__',
          '_^___',
        ],
        [
          '___^_',
          '__^__',
          '_____',
          '_____',
          '_____',
        ],   
        [    
          '_____',
          '___^_',
          '__^__',
          '_____',
          '_____',
        ],   
        [    
          '_____',
          '_____',
          '___^_',
          '__^__',
          '_____',
        ],   
        [    
          '_____',
          '_____',
          '_____',
          '___^_',
          '__^__',
        ],
        [
          '____^',
          '___^_',
          '_____',
          '_____',
          '_____',
        ],    
        [     
          '_____',
          '____^',
          '___^_',
          '_____',
          '_____',
        ],    
        [     
          '_____',
          '_____',
          '____^',
          '___^_',
          '_____',
        ],    
        [     
          '_____',
          '_____',
          '_____',
          '____^',
          '___^_',
        ],
      ],
    },

    {
      id: 'epic_flour',
      level: 'epic',
      type: 'flour',
      name: 'Flour',
      icon: 'E',
      'image': 'images/ingredient_flourgrain_3.png',
      puzzle_shape: [
        '_E',
        '__',
        '_E',
      ],
      possibilities: [],
    },

    {
      id: 'epic_seafood',
      level: 'epic',
      type: 'seafood',
      name: 'Seafood',
      icon: '$',
      image: 'images/ingredient_seafood_3.png',
      puzzle_shape: [
        '$__',
        '___',
        '$_$',
      ],
      possibilities: [],
    },

    {
      id: 'epic_dairy',
      level: 'epic',
      type: 'dairy',
      name: 'Dairy',
      icon: 'B',
      'image': 'images/ingredient_dairyegg_3.png',
      puzzle_shape: [
        'B__',
        '___',
        '__B',
      ],
      possibilities: [],
    },

    {
      id: 'epic_spice',
      level: 'epic',
      type: 'spice',
      name: 'Spice & Sauce',
      icon: '/',
      image: 'images/ingredient_spicesauce_3.png',
      puzzle_shape: [
        '_/',
        '__',
        '__',
        '/_',
      ],
      possibilities: [
        [
          '_/___',
          '_____',
          '_____',
          '/____',
          '_____',
        ],
        [
          '_____',
          '_/___',
          '_____',
          '_____',
          '/____',
        ],
        [
          '__/__',
          '_____',
          '_____',
          '_/___',
          '_____',
        ],  
        [   
          '_____',
          '__/__',
          '_____',
          '_____',
          '_/___',
        ],
        [
          '___/_',
          '_____',
          '_____',
          '__/__',
          '_____',
        ],   
        [    
          '_____',
          '___/_',
          '_____',
          '_____',
          '__/__',
        ],
        [
          '____/',
          '_____',
          '_____',
          '___/_',
          '_____',
        ],    
        [     
          '_____',
          '____/',
          '_____',
          '_____',
          '___/_',
        ],
      ],
    },

    //--- template ----
    /*
    {
      id: 'normal_spice',
      level: 'normal',
      type: 'spice',
      name: 'Spice & Sauce',
      icon: 'A',
      puzzle_shape: [
        '_A_',
        '___',
        '_A_',
        'A_A',
      ],
      possibilities: [],
    },
    */
  ],
};

const getters = {
  normalIngredients(state) {
    return state.ingredients.filter((ing) => {
      return ing.level === 'normal';
    });
  },
  rareIngredients(state) {
    return state.ingredients.filter((ing) => {
      return ing.level === 'rare';
    });
  },
  epicIngredients(state) {
    return state.ingredients.filter((ing) => {
      return ing.level === 'epic';
    });
  },
  getById: (state) => (id) => {
    return state.ingredients.find((ing) => {
      return ing.id === id;
    });
  }
};
const actions = {
};
const mutations = {};


export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations
}
